### PR TITLE
Tutorial for detecting low surface brightness galaxies

### PR DESCRIPTION
**Pull request by kadrlica**
This is a PR to track development of a source detection tutorial for low surface brightness galaxies.  This PR tracks development related to issue #54.

**Ready for code review!**

### CODE REVIEW

**Comment by kadrlica** [comment]
The content of this notebook is now more-or-less complete.  The documentation and reliability should be reviewed, but I'm becoming pretty happy with this product.

**Comment by drphilmarshall** [comment]
Excellent! Nice work :-) Who would you like to review it? Perhaps
@SimonKrughoff could suggest a project reviewer, and @Madejski could
comment on readability?

**Comment by kadrlica** [comment]
Both are good suggestions. I was also thinking that Michael Wood-Vasey might be interested if we are going outside the immediate Stack Club.

**Comment by drphilmarshall** [comment]
Good idea. Maybe have a chat with him this week, see if he's interested in
helping out?

**Comment by kadrlica** [comment]
I'm in Chile observing, but if you are willing to mention it to him I'd appreciate it.

**Comment by kadrlica** [comment]
Looking for a review from @johannct. Otherwise prepared to merge.

**Comment by wmwv** [comment]
@kadrlica This is fantastic.  Fabulous introduction to the specific of what the pipeline is doing for detection and measurement with a minimum of extra work (skipping ISR is good to keep this Notebook simple) and a maximum of cool science.

**Pull request merged**
